name:                haskell-battleship
version:             0.1.0.0
github:              "jtonic/haskell-battleship"
license:             BSD3
author:              "Antonel-Ernest Pazargic"
maintainer:          "antonel.pazargic@gmail.com"
copyright:           "2021 Antonel-Ernest Pazargic"

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-unused-top-binds
  - -Wno-orphans
  # - -XNoImplicitPrelude

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-battleship#readme>

tested-with: GHC == 8.10.3

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: empty
    exposed-modules: Empty
    other-modules: []

executables:
  battleship-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - battleship-lib

tests:
  haskell-battleship-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - battleship-lib

internal-libraries:
    battleship-lib:
        source-dirs: src
        exposed-modules: Lib
        other-modules: []
