name:                haskell-battleship
version:             0.1.0.0
github:              "jtonic/haskell-battleship"
license:             BSD3
author:              "Antonel-Ernest Pazargic"
maintainer:          "antonel.pazargic@gmail.com"
copyright:           "2021 Antonel-Ernest Pazargic"

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-unused-top-binds
  - -Wno-orphans
  # - -XNoImplicitPrelude

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/haskell-battleship#readme>

tested-with: GHC == 8.10.3

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: src

executables:
  battleship:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - haskell-battleship

tests:
  battleship-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - haskell-battleship
