name:                haskell-battleship
version:             0.1.0.0
github:              "jtonic/haskell-battleship"
license:             BSD3
author:              "Antonel-Ernest Pazargic"
maintainer:          "antonel.pazargic@gmail.com"
copyright:           "2021 Antonel-Ernest Pazargic"

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - NoImplicitPrelude

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-unused-top-binds
  - -Wno-orphans
  - -XNegativeLiterals
  # - -Wno-unused-imports
  # - -XNoImplicitPrelude

dependencies:
  - base
  - hslogger
  - optparse-applicative
  - rio
  - extra
  - microlens-th

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/haskell-battleship#readme>

library:
    source-dirs: src

executables:
  battleship:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-battleship

tests:
  battleship-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-battleship
      - hspec
