# https://docs.haskellstack.org/en/stable/yaml_configuration/
resolver: lts-17.10
packages:
- .
nix:
  enable: true
  packages:
  - rdkafka
  - zlib
extra-deps:
  - pure-zlib-0.6.7
  - hw-kafka-avro-5.1.0
